### ISSUE TITLE
docs: Rewrite indexing documentation

### ISSUE THREAD

**Issue by VoVAllen** [tensorchord/pgvecto.rs-docs#24]
- How to choose between HNSW and IVFFlat
- Typical scenarios and `create index` examples
- Quantization and fp16

**Comment by gaocegege** [comment]
https://supabase.com/docs/guides/ai/vector-indexes/hnsw-indexes

**Comment by xieydd** [comment]
https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index
