### ISSUE TITLE
feat: Versioning

### ISSUE THREAD

**Issue by cutecutecat** [tensorchord/pgvecto.rs-docs#63]
Difficult to determine the relationship between versions and features.

It might be something like:
- Multiple Sidebars: https://github.com/vuejs/vitepress/issues/109#issuecomment-1817716640
- Extension: https://github.com/vuejs/vitepress/issues/109#issuecomment-1892622097

**Comment by ajiho** [comment]
路过，其实可以迁移到docusaurus，我之前的项目的文档一直都是用vitepress，发现这个工具虽然好看，但是它不支持版本控制，也不知道要什么时候才能支持了，在这之前建议迁移到docusaurus，docusaurus默认的样式颜值也是比较高的。
